apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp:v
  namespace: default
spec:
  selector:
    matchLabels:
      app: myapp:v
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp:v
    spec:
      containers:
      - name: myapp:v
        image: mastashoff/myapp:v1.0
        ports:
        - containerPort: 80
